<a href="https://colab.research.google.com/github/Nilswonderland/my_workings/blob/main/Statistics_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [6]:
import numpy as np
from scipy import stats
import pandas as pd


 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [29]:
numbers = np.random.normal(100.0, 15, 1000)
numbers

array([ 95.16966966,  91.33779693, 108.77354699, 132.30706716,
       110.49384186,  59.22231897,  84.14500328, 111.97835707,
        88.37792591,  94.63177122, 123.3250604 , 110.05310778,
       108.89287024, 104.02470118, 111.90073865, 115.53222596,
        91.55405808, 126.68727925, 106.41313278, 100.63158257,
        90.70047442,  83.30946815,  98.78120134,  99.42652198,
       107.45591718, 101.00372335,  86.25971871,  95.42058135,
        92.94350591,  68.677766  ,  90.62005468, 119.4971724 ,
       106.71786768, 109.43607835, 122.13476579, 112.42146165,
        81.7968804 , 119.37249256,  98.43691133, 108.18149672,
        67.49364545,  86.77495305, 115.57324306, 103.97116352,
        95.88262795,  94.54901718, 100.44857075,  99.95744696,
       111.49184997, 111.58180829,  88.26618437,  96.66564624,
       117.9245352 ,  99.01638663,  71.57300155, 106.62273175,
        94.66144834, 111.1295709 ,  69.91470318,  86.32614814,
       113.17629132, 105.22808706,  75.90762778, 101.57

Compute the **mean**, **median**, and **mode**

In [35]:
mean = np.mean(numbers)
median = np.median(numbers)
mode = stats.mode(numbers)

print("Mean is ", mean) 
print("Median is ", median)
print("Mode is ", mode)



Mean is  99.52966071621861
Median is  99.64855866366875
Mode is  ModeResult(mode=array([44.47347796]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [46]:
min = np.min(numbers)
max = np.max(numbers)
q1 = np.percentile(numbers, 25)
q3 = np.percentile(numbers, 75)
iqr = stats.iqr(numbers)

print("Minumum number is ", min)
print("Maximum number is ", max)
print("Q1 is" , q1)
print("Q3 is ", q3)
print("IQR is ", iqr)


Minumum number is  44.473477963016016
Maximum number is  147.03192903850493
Q1 is 89.25447233150108
Q3 is  109.83585123787643
IQR is  20.58137890637535


Compute the **variance** and **standard deviation**

In [50]:
variance = np.var(numbers)
variance


224.68656131270004

In [51]:
std_dev = np.std(numbers)
std_dev

14.989548402560366

Compute the **skewness** and **kurtosis**

In [53]:
skewness = stats.skew(numbers)
kurtosis = stats.kurtosis(numbers)
print("Skewness is ", skewness)
print("Kurtosis is ", kurtosis)

Skewness is  -0.03728086653556152
Kurtosis is  -0.016376410765357008


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [55]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [64]:
y = np.random.randint(100, size = 10)
y

array([34, 40, 73, 92, 98, 77,  8, 86, 86,  4])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [65]:
r = np.corrcoef(x,y)
r

array([[ 1.        , -0.08116761],
       [-0.08116761,  1.        ]])

## Pandas Correlation Calculation

Run the code below

In [66]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [67]:
r = x.corr(y)
r

0.7586402890911867

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [69]:
rho = x.corr(y, method= "spearman")
rho

0.9757575757575757

## Seaborn Dataset Tips

Import Seaborn Library

In [71]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [72]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [74]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [76]:
tips.corr("pearson")

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000